version: '3.5'
networks:
    proxy:
        name: proxy
        external: true

services:
  hostalSarita:
      build:
        context: .
        dockerfile: Dockerfile
      image: 'hostalsarita:latest'
      container_name: hostalsarita
      restart: always
      networks:
          - proxy


